version: '2.3'
services:
  jaeger:
    image: jaegertracing/all-in-one:1.8
    expose:
      - 5775/udp
      - 6831/udp
      - 6832/udp
      - 5778
      - 16686
      - 14268
      - 9411
    ports:
      - 16686:16686
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411

  database:
    image: quay.io/azavea/postgis:2.3-postgres9.6-slim
    environment:
      - POSTGRES_USER=tracingdemos
      - POSTGRES_PASSWORD=tracingdemos
      - POSTGRES_DB=tracingdemos
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "tracingdemos"]
      interval: 3s
      timeout: 3s
      retries: 3
      start_period: 5s

  app-backend:
    image: openjdk:11-jdk
    command:
      - "api/run"
    depends_on:
      database:
        condition: service_healthy
    entrypoint: java
    command:
      - "-jar"
      - "tracingdemos-api-assembly.jar"
    environment:
      - AWS_PROFILE
      - ENVIRONMENT=development
      - POSTGRES_URL=jdbc:postgresql://database.service.internal/
      - POSTGRES_NAME=tracingdemos
      - POSTGRES_USER=tracingdemos
      - POSTGRES_PASSWORD=tracingdemos
    links:
      - database:database.service.internal
      - jaeger:jaeger.service.internal
    ports:
      - "8080:8080"
    volumes:
      - ./app-backend/:/opt/tracingdemos/app-backend/
      - $HOME/.sbt:/root/.sbt
      - $HOME/.coursier:/root/.coursier
      - ./.bintray:/root/.bintray
      - $HOME/.ivy2:/root/.ivy2
      - $HOME/.aws:/root/.aws:ro
    working_dir: /opt/tracingdemos/app-backend/api/target/scala-2.12/

  sbt:
    image: hseeberger/scala-sbt:11.0.2_2.12.8_1.2.8
    depends_on:
      database:
        condition: service_healthy
    links:
      - database:database.service.internal
    environment:
      - AWS_PROFILE
      - POSTGRES_URL=jdbc:postgresql://database.service.internal/
      - POSTGRES_NAME=tracingdemos
      - POSTGRES_USER=tracingdemos
      - POSTGRES_PASSWORD=tracingdemos
      - COURSIER_CACHE=/root/.coursier
    volumes:
      - ./app-backend:/opt/tracingdemos
      - $HOME/.sbt:/root/.sbt
      - $HOME/.coursier:/root/.coursier
      - ./.bintray:/root/.bintray
      - $HOME/.ivy2:/root/.ivy2
      - $HOME/.aws:/root/.aws:ro
    working_dir: /opt/tracingdemos/
    entrypoint: sbt

  app-backend-migrations:
    image: boxfuse/flyway:5.2.4
    environment:
      - FLYWAY_DRIVER=org.postgresql.Driver
      - FLYWAY_URL=jdbc:postgresql://database.service.internal/tracingdemos
      - FLYWAY_USER=tracingdemos
      - FLYWAY_PASSWORD=tracingdemos
      - FLYWAY_LOCATIONS=filesystem:/opt/tracingdemos/database/src/main/resources/db
      - FLYWAY_SCHEMAS=public
      - FLYWAY_BASELINE_ON_MIGRATE=true
    depends_on:
      database:
        condition: service_healthy
    links:
      - database:database.service.internal
    volumes:
      - ./app-backend:/opt/tracingdemos
