---
- name: Set AWS_PROFILE
  lineinfile:
    path: "/etc/environment"
    regexp: "^AWS_PROFILE="
    line: "AWS_PROFILE={{ aws_profile }}"

- name: Set DEV_USER environment variable
  lineinfile:
    dest: /etc/environment
    regexp: ^DEV_USER
    line: "DEV_USER={{ dev_user }}"
